/*
BMLT

BMLT Admin API Documentation

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bmlt

import (
	"encoding/json"
)

// checks if the ServiceBodyBase type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServiceBodyBase{}

// ServiceBodyBase struct for ServiceBodyBase
type ServiceBodyBase struct {
	ParentId NullableInt32 `json:"parentId,omitempty"`
	Name *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	Type *string `json:"type,omitempty"`
	AdminUserId *int32 `json:"adminUserId,omitempty"`
	AssignedUserIds []int32 `json:"assignedUserIds,omitempty"`
	Url *string `json:"url,omitempty"`
	Helpline *string `json:"helpline,omitempty"`
	Email *string `json:"email,omitempty"`
	WorldId *string `json:"worldId,omitempty"`
}

// NewServiceBodyBase instantiates a new ServiceBodyBase object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceBodyBase() *ServiceBodyBase {
	this := ServiceBodyBase{}
	return &this
}

// NewServiceBodyBaseWithDefaults instantiates a new ServiceBodyBase object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceBodyBaseWithDefaults() *ServiceBodyBase {
	this := ServiceBodyBase{}
	return &this
}

// GetParentId returns the ParentId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ServiceBodyBase) GetParentId() int32 {
	if o == nil || IsNil(o.ParentId.Get()) {
		var ret int32
		return ret
	}
	return *o.ParentId.Get()
}

// GetParentIdOk returns a tuple with the ParentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ServiceBodyBase) GetParentIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ParentId.Get(), o.ParentId.IsSet()
}

// HasParentId returns a boolean if a field has been set.
func (o *ServiceBodyBase) HasParentId() bool {
	if o != nil && o.ParentId.IsSet() {
		return true
	}

	return false
}

// SetParentId gets a reference to the given NullableInt32 and assigns it to the ParentId field.
func (o *ServiceBodyBase) SetParentId(v int32) {
	o.ParentId.Set(&v)
}
// SetParentIdNil sets the value for ParentId to be an explicit nil
func (o *ServiceBodyBase) SetParentIdNil() {
	o.ParentId.Set(nil)
}

// UnsetParentId ensures that no value is present for ParentId, not even an explicit nil
func (o *ServiceBodyBase) UnsetParentId() {
	o.ParentId.Unset()
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ServiceBodyBase) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceBodyBase) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ServiceBodyBase) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ServiceBodyBase) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ServiceBodyBase) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceBodyBase) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ServiceBodyBase) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ServiceBodyBase) SetDescription(v string) {
	o.Description = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ServiceBodyBase) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceBodyBase) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ServiceBodyBase) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ServiceBodyBase) SetType(v string) {
	o.Type = &v
}

// GetAdminUserId returns the AdminUserId field value if set, zero value otherwise.
func (o *ServiceBodyBase) GetAdminUserId() int32 {
	if o == nil || IsNil(o.AdminUserId) {
		var ret int32
		return ret
	}
	return *o.AdminUserId
}

// GetAdminUserIdOk returns a tuple with the AdminUserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceBodyBase) GetAdminUserIdOk() (*int32, bool) {
	if o == nil || IsNil(o.AdminUserId) {
		return nil, false
	}
	return o.AdminUserId, true
}

// HasAdminUserId returns a boolean if a field has been set.
func (o *ServiceBodyBase) HasAdminUserId() bool {
	if o != nil && !IsNil(o.AdminUserId) {
		return true
	}

	return false
}

// SetAdminUserId gets a reference to the given int32 and assigns it to the AdminUserId field.
func (o *ServiceBodyBase) SetAdminUserId(v int32) {
	o.AdminUserId = &v
}

// GetAssignedUserIds returns the AssignedUserIds field value if set, zero value otherwise.
func (o *ServiceBodyBase) GetAssignedUserIds() []int32 {
	if o == nil || IsNil(o.AssignedUserIds) {
		var ret []int32
		return ret
	}
	return o.AssignedUserIds
}

// GetAssignedUserIdsOk returns a tuple with the AssignedUserIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceBodyBase) GetAssignedUserIdsOk() ([]int32, bool) {
	if o == nil || IsNil(o.AssignedUserIds) {
		return nil, false
	}
	return o.AssignedUserIds, true
}

// HasAssignedUserIds returns a boolean if a field has been set.
func (o *ServiceBodyBase) HasAssignedUserIds() bool {
	if o != nil && !IsNil(o.AssignedUserIds) {
		return true
	}

	return false
}

// SetAssignedUserIds gets a reference to the given []int32 and assigns it to the AssignedUserIds field.
func (o *ServiceBodyBase) SetAssignedUserIds(v []int32) {
	o.AssignedUserIds = v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *ServiceBodyBase) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceBodyBase) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *ServiceBodyBase) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *ServiceBodyBase) SetUrl(v string) {
	o.Url = &v
}

// GetHelpline returns the Helpline field value if set, zero value otherwise.
func (o *ServiceBodyBase) GetHelpline() string {
	if o == nil || IsNil(o.Helpline) {
		var ret string
		return ret
	}
	return *o.Helpline
}

// GetHelplineOk returns a tuple with the Helpline field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceBodyBase) GetHelplineOk() (*string, bool) {
	if o == nil || IsNil(o.Helpline) {
		return nil, false
	}
	return o.Helpline, true
}

// HasHelpline returns a boolean if a field has been set.
func (o *ServiceBodyBase) HasHelpline() bool {
	if o != nil && !IsNil(o.Helpline) {
		return true
	}

	return false
}

// SetHelpline gets a reference to the given string and assigns it to the Helpline field.
func (o *ServiceBodyBase) SetHelpline(v string) {
	o.Helpline = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *ServiceBodyBase) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceBodyBase) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *ServiceBodyBase) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *ServiceBodyBase) SetEmail(v string) {
	o.Email = &v
}

// GetWorldId returns the WorldId field value if set, zero value otherwise.
func (o *ServiceBodyBase) GetWorldId() string {
	if o == nil || IsNil(o.WorldId) {
		var ret string
		return ret
	}
	return *o.WorldId
}

// GetWorldIdOk returns a tuple with the WorldId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceBodyBase) GetWorldIdOk() (*string, bool) {
	if o == nil || IsNil(o.WorldId) {
		return nil, false
	}
	return o.WorldId, true
}

// HasWorldId returns a boolean if a field has been set.
func (o *ServiceBodyBase) HasWorldId() bool {
	if o != nil && !IsNil(o.WorldId) {
		return true
	}

	return false
}

// SetWorldId gets a reference to the given string and assigns it to the WorldId field.
func (o *ServiceBodyBase) SetWorldId(v string) {
	o.WorldId = &v
}

func (o ServiceBodyBase) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServiceBodyBase) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.ParentId.IsSet() {
		toSerialize["parentId"] = o.ParentId.Get()
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.AdminUserId) {
		toSerialize["adminUserId"] = o.AdminUserId
	}
	if !IsNil(o.AssignedUserIds) {
		toSerialize["assignedUserIds"] = o.AssignedUserIds
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.Helpline) {
		toSerialize["helpline"] = o.Helpline
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.WorldId) {
		toSerialize["worldId"] = o.WorldId
	}
	return toSerialize, nil
}

type NullableServiceBodyBase struct {
	value *ServiceBodyBase
	isSet bool
}

func (v NullableServiceBodyBase) Get() *ServiceBodyBase {
	return v.value
}

func (v *NullableServiceBodyBase) Set(val *ServiceBodyBase) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceBodyBase) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceBodyBase) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceBodyBase(val *ServiceBodyBase) *NullableServiceBodyBase {
	return &NullableServiceBodyBase{value: val, isSet: true}
}

func (v NullableServiceBodyBase) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceBodyBase) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


