/*
BMLT

BMLT Admin API Documentation

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bmlt

import (
	"encoding/json"
)

// checks if the SettingsUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SettingsUpdate{}

// SettingsUpdate Partial update object - include only the settings you want to update
type SettingsUpdate struct {
	GoogleApiKey *string `json:"googleApiKey,omitempty"`
	ChangeDepthForMeetings *int32 `json:"changeDepthForMeetings,omitempty"`
	DefaultSortKey NullableString `json:"defaultSortKey,omitempty"`
	Language *string `json:"language,omitempty"`
	DefaultDurationTime *string `json:"defaultDurationTime,omitempty"`
	RegionBias *string `json:"regionBias,omitempty"`
	DistanceUnits *string `json:"distanceUnits,omitempty"`
	MeetingStatesAndProvinces []string `json:"meetingStatesAndProvinces,omitempty"`
	MeetingCountiesAndSubProvinces []string `json:"meetingCountiesAndSubProvinces,omitempty"`
	SearchSpecMapCenterLongitude *float32 `json:"searchSpecMapCenterLongitude,omitempty"`
	SearchSpecMapCenterLatitude *float32 `json:"searchSpecMapCenterLatitude,omitempty"`
	SearchSpecMapCenterZoom *int32 `json:"searchSpecMapCenterZoom,omitempty"`
	NumberOfMeetingsForAuto *int32 `json:"numberOfMeetingsForAuto,omitempty"`
	AutoGeocodingEnabled *bool `json:"autoGeocodingEnabled,omitempty"`
	CountyAutoGeocodingEnabled *bool `json:"countyAutoGeocodingEnabled,omitempty"`
	ZipAutoGeocodingEnabled *bool `json:"zipAutoGeocodingEnabled,omitempty"`
	DefaultClosedStatus *bool `json:"defaultClosedStatus,omitempty"`
	EnableLanguageSelector *bool `json:"enableLanguageSelector,omitempty"`
	IncludeServiceBodyEmailInSemantic *bool `json:"includeServiceBodyEmailInSemantic,omitempty"`
	BmltTitle *string `json:"bmltTitle,omitempty"`
	BmltNotice *string `json:"bmltNotice,omitempty"`
	FormatLangNames map[string]interface{} `json:"formatLangNames,omitempty"`
}

// NewSettingsUpdate instantiates a new SettingsUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSettingsUpdate() *SettingsUpdate {
	this := SettingsUpdate{}
	return &this
}

// NewSettingsUpdateWithDefaults instantiates a new SettingsUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSettingsUpdateWithDefaults() *SettingsUpdate {
	this := SettingsUpdate{}
	return &this
}

// GetGoogleApiKey returns the GoogleApiKey field value if set, zero value otherwise.
func (o *SettingsUpdate) GetGoogleApiKey() string {
	if o == nil || IsNil(o.GoogleApiKey) {
		var ret string
		return ret
	}
	return *o.GoogleApiKey
}

// GetGoogleApiKeyOk returns a tuple with the GoogleApiKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsUpdate) GetGoogleApiKeyOk() (*string, bool) {
	if o == nil || IsNil(o.GoogleApiKey) {
		return nil, false
	}
	return o.GoogleApiKey, true
}

// HasGoogleApiKey returns a boolean if a field has been set.
func (o *SettingsUpdate) HasGoogleApiKey() bool {
	if o != nil && !IsNil(o.GoogleApiKey) {
		return true
	}

	return false
}

// SetGoogleApiKey gets a reference to the given string and assigns it to the GoogleApiKey field.
func (o *SettingsUpdate) SetGoogleApiKey(v string) {
	o.GoogleApiKey = &v
}

// GetChangeDepthForMeetings returns the ChangeDepthForMeetings field value if set, zero value otherwise.
func (o *SettingsUpdate) GetChangeDepthForMeetings() int32 {
	if o == nil || IsNil(o.ChangeDepthForMeetings) {
		var ret int32
		return ret
	}
	return *o.ChangeDepthForMeetings
}

// GetChangeDepthForMeetingsOk returns a tuple with the ChangeDepthForMeetings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsUpdate) GetChangeDepthForMeetingsOk() (*int32, bool) {
	if o == nil || IsNil(o.ChangeDepthForMeetings) {
		return nil, false
	}
	return o.ChangeDepthForMeetings, true
}

// HasChangeDepthForMeetings returns a boolean if a field has been set.
func (o *SettingsUpdate) HasChangeDepthForMeetings() bool {
	if o != nil && !IsNil(o.ChangeDepthForMeetings) {
		return true
	}

	return false
}

// SetChangeDepthForMeetings gets a reference to the given int32 and assigns it to the ChangeDepthForMeetings field.
func (o *SettingsUpdate) SetChangeDepthForMeetings(v int32) {
	o.ChangeDepthForMeetings = &v
}

// GetDefaultSortKey returns the DefaultSortKey field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SettingsUpdate) GetDefaultSortKey() string {
	if o == nil || IsNil(o.DefaultSortKey.Get()) {
		var ret string
		return ret
	}
	return *o.DefaultSortKey.Get()
}

// GetDefaultSortKeyOk returns a tuple with the DefaultSortKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SettingsUpdate) GetDefaultSortKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DefaultSortKey.Get(), o.DefaultSortKey.IsSet()
}

// HasDefaultSortKey returns a boolean if a field has been set.
func (o *SettingsUpdate) HasDefaultSortKey() bool {
	if o != nil && o.DefaultSortKey.IsSet() {
		return true
	}

	return false
}

// SetDefaultSortKey gets a reference to the given NullableString and assigns it to the DefaultSortKey field.
func (o *SettingsUpdate) SetDefaultSortKey(v string) {
	o.DefaultSortKey.Set(&v)
}
// SetDefaultSortKeyNil sets the value for DefaultSortKey to be an explicit nil
func (o *SettingsUpdate) SetDefaultSortKeyNil() {
	o.DefaultSortKey.Set(nil)
}

// UnsetDefaultSortKey ensures that no value is present for DefaultSortKey, not even an explicit nil
func (o *SettingsUpdate) UnsetDefaultSortKey() {
	o.DefaultSortKey.Unset()
}

// GetLanguage returns the Language field value if set, zero value otherwise.
func (o *SettingsUpdate) GetLanguage() string {
	if o == nil || IsNil(o.Language) {
		var ret string
		return ret
	}
	return *o.Language
}

// GetLanguageOk returns a tuple with the Language field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsUpdate) GetLanguageOk() (*string, bool) {
	if o == nil || IsNil(o.Language) {
		return nil, false
	}
	return o.Language, true
}

// HasLanguage returns a boolean if a field has been set.
func (o *SettingsUpdate) HasLanguage() bool {
	if o != nil && !IsNil(o.Language) {
		return true
	}

	return false
}

// SetLanguage gets a reference to the given string and assigns it to the Language field.
func (o *SettingsUpdate) SetLanguage(v string) {
	o.Language = &v
}

// GetDefaultDurationTime returns the DefaultDurationTime field value if set, zero value otherwise.
func (o *SettingsUpdate) GetDefaultDurationTime() string {
	if o == nil || IsNil(o.DefaultDurationTime) {
		var ret string
		return ret
	}
	return *o.DefaultDurationTime
}

// GetDefaultDurationTimeOk returns a tuple with the DefaultDurationTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsUpdate) GetDefaultDurationTimeOk() (*string, bool) {
	if o == nil || IsNil(o.DefaultDurationTime) {
		return nil, false
	}
	return o.DefaultDurationTime, true
}

// HasDefaultDurationTime returns a boolean if a field has been set.
func (o *SettingsUpdate) HasDefaultDurationTime() bool {
	if o != nil && !IsNil(o.DefaultDurationTime) {
		return true
	}

	return false
}

// SetDefaultDurationTime gets a reference to the given string and assigns it to the DefaultDurationTime field.
func (o *SettingsUpdate) SetDefaultDurationTime(v string) {
	o.DefaultDurationTime = &v
}

// GetRegionBias returns the RegionBias field value if set, zero value otherwise.
func (o *SettingsUpdate) GetRegionBias() string {
	if o == nil || IsNil(o.RegionBias) {
		var ret string
		return ret
	}
	return *o.RegionBias
}

// GetRegionBiasOk returns a tuple with the RegionBias field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsUpdate) GetRegionBiasOk() (*string, bool) {
	if o == nil || IsNil(o.RegionBias) {
		return nil, false
	}
	return o.RegionBias, true
}

// HasRegionBias returns a boolean if a field has been set.
func (o *SettingsUpdate) HasRegionBias() bool {
	if o != nil && !IsNil(o.RegionBias) {
		return true
	}

	return false
}

// SetRegionBias gets a reference to the given string and assigns it to the RegionBias field.
func (o *SettingsUpdate) SetRegionBias(v string) {
	o.RegionBias = &v
}

// GetDistanceUnits returns the DistanceUnits field value if set, zero value otherwise.
func (o *SettingsUpdate) GetDistanceUnits() string {
	if o == nil || IsNil(o.DistanceUnits) {
		var ret string
		return ret
	}
	return *o.DistanceUnits
}

// GetDistanceUnitsOk returns a tuple with the DistanceUnits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsUpdate) GetDistanceUnitsOk() (*string, bool) {
	if o == nil || IsNil(o.DistanceUnits) {
		return nil, false
	}
	return o.DistanceUnits, true
}

// HasDistanceUnits returns a boolean if a field has been set.
func (o *SettingsUpdate) HasDistanceUnits() bool {
	if o != nil && !IsNil(o.DistanceUnits) {
		return true
	}

	return false
}

// SetDistanceUnits gets a reference to the given string and assigns it to the DistanceUnits field.
func (o *SettingsUpdate) SetDistanceUnits(v string) {
	o.DistanceUnits = &v
}

// GetMeetingStatesAndProvinces returns the MeetingStatesAndProvinces field value if set, zero value otherwise.
func (o *SettingsUpdate) GetMeetingStatesAndProvinces() []string {
	if o == nil || IsNil(o.MeetingStatesAndProvinces) {
		var ret []string
		return ret
	}
	return o.MeetingStatesAndProvinces
}

// GetMeetingStatesAndProvincesOk returns a tuple with the MeetingStatesAndProvinces field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsUpdate) GetMeetingStatesAndProvincesOk() ([]string, bool) {
	if o == nil || IsNil(o.MeetingStatesAndProvinces) {
		return nil, false
	}
	return o.MeetingStatesAndProvinces, true
}

// HasMeetingStatesAndProvinces returns a boolean if a field has been set.
func (o *SettingsUpdate) HasMeetingStatesAndProvinces() bool {
	if o != nil && !IsNil(o.MeetingStatesAndProvinces) {
		return true
	}

	return false
}

// SetMeetingStatesAndProvinces gets a reference to the given []string and assigns it to the MeetingStatesAndProvinces field.
func (o *SettingsUpdate) SetMeetingStatesAndProvinces(v []string) {
	o.MeetingStatesAndProvinces = v
}

// GetMeetingCountiesAndSubProvinces returns the MeetingCountiesAndSubProvinces field value if set, zero value otherwise.
func (o *SettingsUpdate) GetMeetingCountiesAndSubProvinces() []string {
	if o == nil || IsNil(o.MeetingCountiesAndSubProvinces) {
		var ret []string
		return ret
	}
	return o.MeetingCountiesAndSubProvinces
}

// GetMeetingCountiesAndSubProvincesOk returns a tuple with the MeetingCountiesAndSubProvinces field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsUpdate) GetMeetingCountiesAndSubProvincesOk() ([]string, bool) {
	if o == nil || IsNil(o.MeetingCountiesAndSubProvinces) {
		return nil, false
	}
	return o.MeetingCountiesAndSubProvinces, true
}

// HasMeetingCountiesAndSubProvinces returns a boolean if a field has been set.
func (o *SettingsUpdate) HasMeetingCountiesAndSubProvinces() bool {
	if o != nil && !IsNil(o.MeetingCountiesAndSubProvinces) {
		return true
	}

	return false
}

// SetMeetingCountiesAndSubProvinces gets a reference to the given []string and assigns it to the MeetingCountiesAndSubProvinces field.
func (o *SettingsUpdate) SetMeetingCountiesAndSubProvinces(v []string) {
	o.MeetingCountiesAndSubProvinces = v
}

// GetSearchSpecMapCenterLongitude returns the SearchSpecMapCenterLongitude field value if set, zero value otherwise.
func (o *SettingsUpdate) GetSearchSpecMapCenterLongitude() float32 {
	if o == nil || IsNil(o.SearchSpecMapCenterLongitude) {
		var ret float32
		return ret
	}
	return *o.SearchSpecMapCenterLongitude
}

// GetSearchSpecMapCenterLongitudeOk returns a tuple with the SearchSpecMapCenterLongitude field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsUpdate) GetSearchSpecMapCenterLongitudeOk() (*float32, bool) {
	if o == nil || IsNil(o.SearchSpecMapCenterLongitude) {
		return nil, false
	}
	return o.SearchSpecMapCenterLongitude, true
}

// HasSearchSpecMapCenterLongitude returns a boolean if a field has been set.
func (o *SettingsUpdate) HasSearchSpecMapCenterLongitude() bool {
	if o != nil && !IsNil(o.SearchSpecMapCenterLongitude) {
		return true
	}

	return false
}

// SetSearchSpecMapCenterLongitude gets a reference to the given float32 and assigns it to the SearchSpecMapCenterLongitude field.
func (o *SettingsUpdate) SetSearchSpecMapCenterLongitude(v float32) {
	o.SearchSpecMapCenterLongitude = &v
}

// GetSearchSpecMapCenterLatitude returns the SearchSpecMapCenterLatitude field value if set, zero value otherwise.
func (o *SettingsUpdate) GetSearchSpecMapCenterLatitude() float32 {
	if o == nil || IsNil(o.SearchSpecMapCenterLatitude) {
		var ret float32
		return ret
	}
	return *o.SearchSpecMapCenterLatitude
}

// GetSearchSpecMapCenterLatitudeOk returns a tuple with the SearchSpecMapCenterLatitude field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsUpdate) GetSearchSpecMapCenterLatitudeOk() (*float32, bool) {
	if o == nil || IsNil(o.SearchSpecMapCenterLatitude) {
		return nil, false
	}
	return o.SearchSpecMapCenterLatitude, true
}

// HasSearchSpecMapCenterLatitude returns a boolean if a field has been set.
func (o *SettingsUpdate) HasSearchSpecMapCenterLatitude() bool {
	if o != nil && !IsNil(o.SearchSpecMapCenterLatitude) {
		return true
	}

	return false
}

// SetSearchSpecMapCenterLatitude gets a reference to the given float32 and assigns it to the SearchSpecMapCenterLatitude field.
func (o *SettingsUpdate) SetSearchSpecMapCenterLatitude(v float32) {
	o.SearchSpecMapCenterLatitude = &v
}

// GetSearchSpecMapCenterZoom returns the SearchSpecMapCenterZoom field value if set, zero value otherwise.
func (o *SettingsUpdate) GetSearchSpecMapCenterZoom() int32 {
	if o == nil || IsNil(o.SearchSpecMapCenterZoom) {
		var ret int32
		return ret
	}
	return *o.SearchSpecMapCenterZoom
}

// GetSearchSpecMapCenterZoomOk returns a tuple with the SearchSpecMapCenterZoom field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsUpdate) GetSearchSpecMapCenterZoomOk() (*int32, bool) {
	if o == nil || IsNil(o.SearchSpecMapCenterZoom) {
		return nil, false
	}
	return o.SearchSpecMapCenterZoom, true
}

// HasSearchSpecMapCenterZoom returns a boolean if a field has been set.
func (o *SettingsUpdate) HasSearchSpecMapCenterZoom() bool {
	if o != nil && !IsNil(o.SearchSpecMapCenterZoom) {
		return true
	}

	return false
}

// SetSearchSpecMapCenterZoom gets a reference to the given int32 and assigns it to the SearchSpecMapCenterZoom field.
func (o *SettingsUpdate) SetSearchSpecMapCenterZoom(v int32) {
	o.SearchSpecMapCenterZoom = &v
}

// GetNumberOfMeetingsForAuto returns the NumberOfMeetingsForAuto field value if set, zero value otherwise.
func (o *SettingsUpdate) GetNumberOfMeetingsForAuto() int32 {
	if o == nil || IsNil(o.NumberOfMeetingsForAuto) {
		var ret int32
		return ret
	}
	return *o.NumberOfMeetingsForAuto
}

// GetNumberOfMeetingsForAutoOk returns a tuple with the NumberOfMeetingsForAuto field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsUpdate) GetNumberOfMeetingsForAutoOk() (*int32, bool) {
	if o == nil || IsNil(o.NumberOfMeetingsForAuto) {
		return nil, false
	}
	return o.NumberOfMeetingsForAuto, true
}

// HasNumberOfMeetingsForAuto returns a boolean if a field has been set.
func (o *SettingsUpdate) HasNumberOfMeetingsForAuto() bool {
	if o != nil && !IsNil(o.NumberOfMeetingsForAuto) {
		return true
	}

	return false
}

// SetNumberOfMeetingsForAuto gets a reference to the given int32 and assigns it to the NumberOfMeetingsForAuto field.
func (o *SettingsUpdate) SetNumberOfMeetingsForAuto(v int32) {
	o.NumberOfMeetingsForAuto = &v
}

// GetAutoGeocodingEnabled returns the AutoGeocodingEnabled field value if set, zero value otherwise.
func (o *SettingsUpdate) GetAutoGeocodingEnabled() bool {
	if o == nil || IsNil(o.AutoGeocodingEnabled) {
		var ret bool
		return ret
	}
	return *o.AutoGeocodingEnabled
}

// GetAutoGeocodingEnabledOk returns a tuple with the AutoGeocodingEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsUpdate) GetAutoGeocodingEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.AutoGeocodingEnabled) {
		return nil, false
	}
	return o.AutoGeocodingEnabled, true
}

// HasAutoGeocodingEnabled returns a boolean if a field has been set.
func (o *SettingsUpdate) HasAutoGeocodingEnabled() bool {
	if o != nil && !IsNil(o.AutoGeocodingEnabled) {
		return true
	}

	return false
}

// SetAutoGeocodingEnabled gets a reference to the given bool and assigns it to the AutoGeocodingEnabled field.
func (o *SettingsUpdate) SetAutoGeocodingEnabled(v bool) {
	o.AutoGeocodingEnabled = &v
}

// GetCountyAutoGeocodingEnabled returns the CountyAutoGeocodingEnabled field value if set, zero value otherwise.
func (o *SettingsUpdate) GetCountyAutoGeocodingEnabled() bool {
	if o == nil || IsNil(o.CountyAutoGeocodingEnabled) {
		var ret bool
		return ret
	}
	return *o.CountyAutoGeocodingEnabled
}

// GetCountyAutoGeocodingEnabledOk returns a tuple with the CountyAutoGeocodingEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsUpdate) GetCountyAutoGeocodingEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.CountyAutoGeocodingEnabled) {
		return nil, false
	}
	return o.CountyAutoGeocodingEnabled, true
}

// HasCountyAutoGeocodingEnabled returns a boolean if a field has been set.
func (o *SettingsUpdate) HasCountyAutoGeocodingEnabled() bool {
	if o != nil && !IsNil(o.CountyAutoGeocodingEnabled) {
		return true
	}

	return false
}

// SetCountyAutoGeocodingEnabled gets a reference to the given bool and assigns it to the CountyAutoGeocodingEnabled field.
func (o *SettingsUpdate) SetCountyAutoGeocodingEnabled(v bool) {
	o.CountyAutoGeocodingEnabled = &v
}

// GetZipAutoGeocodingEnabled returns the ZipAutoGeocodingEnabled field value if set, zero value otherwise.
func (o *SettingsUpdate) GetZipAutoGeocodingEnabled() bool {
	if o == nil || IsNil(o.ZipAutoGeocodingEnabled) {
		var ret bool
		return ret
	}
	return *o.ZipAutoGeocodingEnabled
}

// GetZipAutoGeocodingEnabledOk returns a tuple with the ZipAutoGeocodingEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsUpdate) GetZipAutoGeocodingEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.ZipAutoGeocodingEnabled) {
		return nil, false
	}
	return o.ZipAutoGeocodingEnabled, true
}

// HasZipAutoGeocodingEnabled returns a boolean if a field has been set.
func (o *SettingsUpdate) HasZipAutoGeocodingEnabled() bool {
	if o != nil && !IsNil(o.ZipAutoGeocodingEnabled) {
		return true
	}

	return false
}

// SetZipAutoGeocodingEnabled gets a reference to the given bool and assigns it to the ZipAutoGeocodingEnabled field.
func (o *SettingsUpdate) SetZipAutoGeocodingEnabled(v bool) {
	o.ZipAutoGeocodingEnabled = &v
}

// GetDefaultClosedStatus returns the DefaultClosedStatus field value if set, zero value otherwise.
func (o *SettingsUpdate) GetDefaultClosedStatus() bool {
	if o == nil || IsNil(o.DefaultClosedStatus) {
		var ret bool
		return ret
	}
	return *o.DefaultClosedStatus
}

// GetDefaultClosedStatusOk returns a tuple with the DefaultClosedStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsUpdate) GetDefaultClosedStatusOk() (*bool, bool) {
	if o == nil || IsNil(o.DefaultClosedStatus) {
		return nil, false
	}
	return o.DefaultClosedStatus, true
}

// HasDefaultClosedStatus returns a boolean if a field has been set.
func (o *SettingsUpdate) HasDefaultClosedStatus() bool {
	if o != nil && !IsNil(o.DefaultClosedStatus) {
		return true
	}

	return false
}

// SetDefaultClosedStatus gets a reference to the given bool and assigns it to the DefaultClosedStatus field.
func (o *SettingsUpdate) SetDefaultClosedStatus(v bool) {
	o.DefaultClosedStatus = &v
}

// GetEnableLanguageSelector returns the EnableLanguageSelector field value if set, zero value otherwise.
func (o *SettingsUpdate) GetEnableLanguageSelector() bool {
	if o == nil || IsNil(o.EnableLanguageSelector) {
		var ret bool
		return ret
	}
	return *o.EnableLanguageSelector
}

// GetEnableLanguageSelectorOk returns a tuple with the EnableLanguageSelector field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsUpdate) GetEnableLanguageSelectorOk() (*bool, bool) {
	if o == nil || IsNil(o.EnableLanguageSelector) {
		return nil, false
	}
	return o.EnableLanguageSelector, true
}

// HasEnableLanguageSelector returns a boolean if a field has been set.
func (o *SettingsUpdate) HasEnableLanguageSelector() bool {
	if o != nil && !IsNil(o.EnableLanguageSelector) {
		return true
	}

	return false
}

// SetEnableLanguageSelector gets a reference to the given bool and assigns it to the EnableLanguageSelector field.
func (o *SettingsUpdate) SetEnableLanguageSelector(v bool) {
	o.EnableLanguageSelector = &v
}

// GetIncludeServiceBodyEmailInSemantic returns the IncludeServiceBodyEmailInSemantic field value if set, zero value otherwise.
func (o *SettingsUpdate) GetIncludeServiceBodyEmailInSemantic() bool {
	if o == nil || IsNil(o.IncludeServiceBodyEmailInSemantic) {
		var ret bool
		return ret
	}
	return *o.IncludeServiceBodyEmailInSemantic
}

// GetIncludeServiceBodyEmailInSemanticOk returns a tuple with the IncludeServiceBodyEmailInSemantic field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsUpdate) GetIncludeServiceBodyEmailInSemanticOk() (*bool, bool) {
	if o == nil || IsNil(o.IncludeServiceBodyEmailInSemantic) {
		return nil, false
	}
	return o.IncludeServiceBodyEmailInSemantic, true
}

// HasIncludeServiceBodyEmailInSemantic returns a boolean if a field has been set.
func (o *SettingsUpdate) HasIncludeServiceBodyEmailInSemantic() bool {
	if o != nil && !IsNil(o.IncludeServiceBodyEmailInSemantic) {
		return true
	}

	return false
}

// SetIncludeServiceBodyEmailInSemantic gets a reference to the given bool and assigns it to the IncludeServiceBodyEmailInSemantic field.
func (o *SettingsUpdate) SetIncludeServiceBodyEmailInSemantic(v bool) {
	o.IncludeServiceBodyEmailInSemantic = &v
}

// GetBmltTitle returns the BmltTitle field value if set, zero value otherwise.
func (o *SettingsUpdate) GetBmltTitle() string {
	if o == nil || IsNil(o.BmltTitle) {
		var ret string
		return ret
	}
	return *o.BmltTitle
}

// GetBmltTitleOk returns a tuple with the BmltTitle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsUpdate) GetBmltTitleOk() (*string, bool) {
	if o == nil || IsNil(o.BmltTitle) {
		return nil, false
	}
	return o.BmltTitle, true
}

// HasBmltTitle returns a boolean if a field has been set.
func (o *SettingsUpdate) HasBmltTitle() bool {
	if o != nil && !IsNil(o.BmltTitle) {
		return true
	}

	return false
}

// SetBmltTitle gets a reference to the given string and assigns it to the BmltTitle field.
func (o *SettingsUpdate) SetBmltTitle(v string) {
	o.BmltTitle = &v
}

// GetBmltNotice returns the BmltNotice field value if set, zero value otherwise.
func (o *SettingsUpdate) GetBmltNotice() string {
	if o == nil || IsNil(o.BmltNotice) {
		var ret string
		return ret
	}
	return *o.BmltNotice
}

// GetBmltNoticeOk returns a tuple with the BmltNotice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsUpdate) GetBmltNoticeOk() (*string, bool) {
	if o == nil || IsNil(o.BmltNotice) {
		return nil, false
	}
	return o.BmltNotice, true
}

// HasBmltNotice returns a boolean if a field has been set.
func (o *SettingsUpdate) HasBmltNotice() bool {
	if o != nil && !IsNil(o.BmltNotice) {
		return true
	}

	return false
}

// SetBmltNotice gets a reference to the given string and assigns it to the BmltNotice field.
func (o *SettingsUpdate) SetBmltNotice(v string) {
	o.BmltNotice = &v
}

// GetFormatLangNames returns the FormatLangNames field value if set, zero value otherwise.
func (o *SettingsUpdate) GetFormatLangNames() map[string]interface{} {
	if o == nil || IsNil(o.FormatLangNames) {
		var ret map[string]interface{}
		return ret
	}
	return o.FormatLangNames
}

// GetFormatLangNamesOk returns a tuple with the FormatLangNames field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsUpdate) GetFormatLangNamesOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.FormatLangNames) {
		return map[string]interface{}{}, false
	}
	return o.FormatLangNames, true
}

// HasFormatLangNames returns a boolean if a field has been set.
func (o *SettingsUpdate) HasFormatLangNames() bool {
	if o != nil && !IsNil(o.FormatLangNames) {
		return true
	}

	return false
}

// SetFormatLangNames gets a reference to the given map[string]interface{} and assigns it to the FormatLangNames field.
func (o *SettingsUpdate) SetFormatLangNames(v map[string]interface{}) {
	o.FormatLangNames = v
}

func (o SettingsUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SettingsUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.GoogleApiKey) {
		toSerialize["googleApiKey"] = o.GoogleApiKey
	}
	if !IsNil(o.ChangeDepthForMeetings) {
		toSerialize["changeDepthForMeetings"] = o.ChangeDepthForMeetings
	}
	if o.DefaultSortKey.IsSet() {
		toSerialize["defaultSortKey"] = o.DefaultSortKey.Get()
	}
	if !IsNil(o.Language) {
		toSerialize["language"] = o.Language
	}
	if !IsNil(o.DefaultDurationTime) {
		toSerialize["defaultDurationTime"] = o.DefaultDurationTime
	}
	if !IsNil(o.RegionBias) {
		toSerialize["regionBias"] = o.RegionBias
	}
	if !IsNil(o.DistanceUnits) {
		toSerialize["distanceUnits"] = o.DistanceUnits
	}
	if !IsNil(o.MeetingStatesAndProvinces) {
		toSerialize["meetingStatesAndProvinces"] = o.MeetingStatesAndProvinces
	}
	if !IsNil(o.MeetingCountiesAndSubProvinces) {
		toSerialize["meetingCountiesAndSubProvinces"] = o.MeetingCountiesAndSubProvinces
	}
	if !IsNil(o.SearchSpecMapCenterLongitude) {
		toSerialize["searchSpecMapCenterLongitude"] = o.SearchSpecMapCenterLongitude
	}
	if !IsNil(o.SearchSpecMapCenterLatitude) {
		toSerialize["searchSpecMapCenterLatitude"] = o.SearchSpecMapCenterLatitude
	}
	if !IsNil(o.SearchSpecMapCenterZoom) {
		toSerialize["searchSpecMapCenterZoom"] = o.SearchSpecMapCenterZoom
	}
	if !IsNil(o.NumberOfMeetingsForAuto) {
		toSerialize["numberOfMeetingsForAuto"] = o.NumberOfMeetingsForAuto
	}
	if !IsNil(o.AutoGeocodingEnabled) {
		toSerialize["autoGeocodingEnabled"] = o.AutoGeocodingEnabled
	}
	if !IsNil(o.CountyAutoGeocodingEnabled) {
		toSerialize["countyAutoGeocodingEnabled"] = o.CountyAutoGeocodingEnabled
	}
	if !IsNil(o.ZipAutoGeocodingEnabled) {
		toSerialize["zipAutoGeocodingEnabled"] = o.ZipAutoGeocodingEnabled
	}
	if !IsNil(o.DefaultClosedStatus) {
		toSerialize["defaultClosedStatus"] = o.DefaultClosedStatus
	}
	if !IsNil(o.EnableLanguageSelector) {
		toSerialize["enableLanguageSelector"] = o.EnableLanguageSelector
	}
	if !IsNil(o.IncludeServiceBodyEmailInSemantic) {
		toSerialize["includeServiceBodyEmailInSemantic"] = o.IncludeServiceBodyEmailInSemantic
	}
	if !IsNil(o.BmltTitle) {
		toSerialize["bmltTitle"] = o.BmltTitle
	}
	if !IsNil(o.BmltNotice) {
		toSerialize["bmltNotice"] = o.BmltNotice
	}
	if !IsNil(o.FormatLangNames) {
		toSerialize["formatLangNames"] = o.FormatLangNames
	}
	return toSerialize, nil
}

type NullableSettingsUpdate struct {
	value *SettingsUpdate
	isSet bool
}

func (v NullableSettingsUpdate) Get() *SettingsUpdate {
	return v.value
}

func (v *NullableSettingsUpdate) Set(val *SettingsUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableSettingsUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableSettingsUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSettingsUpdate(val *SettingsUpdate) *NullableSettingsUpdate {
	return &NullableSettingsUpdate{value: val, isSet: true}
}

func (v NullableSettingsUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSettingsUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


