/*
BMLT

BMLT Admin API Documentation

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bmlt

import (
	"encoding/json"
)

// UserCreateAllOf struct for UserCreateAllOf
type UserCreateAllOf struct {
	Password *string `json:"password,omitempty"`
}

// NewUserCreateAllOf instantiates a new UserCreateAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserCreateAllOf() *UserCreateAllOf {
	this := UserCreateAllOf{}
	return &this
}

// NewUserCreateAllOfWithDefaults instantiates a new UserCreateAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserCreateAllOfWithDefaults() *UserCreateAllOf {
	this := UserCreateAllOf{}
	return &this
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *UserCreateAllOf) GetPassword() string {
	if o == nil || o.Password == nil {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserCreateAllOf) GetPasswordOk() (*string, bool) {
	if o == nil || o.Password == nil {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *UserCreateAllOf) HasPassword() bool {
	if o != nil && o.Password != nil {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *UserCreateAllOf) SetPassword(v string) {
	o.Password = &v
}

func (o UserCreateAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Password != nil {
		toSerialize["password"] = o.Password
	}
	return json.Marshal(toSerialize)
}

type NullableUserCreateAllOf struct {
	value *UserCreateAllOf
	isSet bool
}

func (v NullableUserCreateAllOf) Get() *UserCreateAllOf {
	return v.value
}

func (v *NullableUserCreateAllOf) Set(val *UserCreateAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableUserCreateAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableUserCreateAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserCreateAllOf(val *UserCreateAllOf) *NullableUserCreateAllOf {
	return &NullableUserCreateAllOf{value: val, isSet: true}
}

func (v NullableUserCreateAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserCreateAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


