/*
BMLT

BMLT Admin API Documentation

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bmlt

import (
	"encoding/json"
)

// FormatCreate struct for FormatCreate
type FormatCreate struct {
	WorldId *string `json:"worldId,omitempty"`
	Type *string `json:"type,omitempty"`
	Translations []FormatTranslation `json:"translations"`
}

// NewFormatCreate instantiates a new FormatCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFormatCreate(translations []FormatTranslation) *FormatCreate {
	this := FormatCreate{}
	this.Translations = translations
	return &this
}

// NewFormatCreateWithDefaults instantiates a new FormatCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFormatCreateWithDefaults() *FormatCreate {
	this := FormatCreate{}
	return &this
}

// GetWorldId returns the WorldId field value if set, zero value otherwise.
func (o *FormatCreate) GetWorldId() string {
	if o == nil || o.WorldId == nil {
		var ret string
		return ret
	}
	return *o.WorldId
}

// GetWorldIdOk returns a tuple with the WorldId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FormatCreate) GetWorldIdOk() (*string, bool) {
	if o == nil || o.WorldId == nil {
		return nil, false
	}
	return o.WorldId, true
}

// HasWorldId returns a boolean if a field has been set.
func (o *FormatCreate) HasWorldId() bool {
	if o != nil && o.WorldId != nil {
		return true
	}

	return false
}

// SetWorldId gets a reference to the given string and assigns it to the WorldId field.
func (o *FormatCreate) SetWorldId(v string) {
	o.WorldId = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *FormatCreate) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FormatCreate) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *FormatCreate) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *FormatCreate) SetType(v string) {
	o.Type = &v
}

// GetTranslations returns the Translations field value
func (o *FormatCreate) GetTranslations() []FormatTranslation {
	if o == nil {
		var ret []FormatTranslation
		return ret
	}

	return o.Translations
}

// GetTranslationsOk returns a tuple with the Translations field value
// and a boolean to check if the value has been set.
func (o *FormatCreate) GetTranslationsOk() ([]FormatTranslation, bool) {
	if o == nil {
		return nil, false
	}
	return o.Translations, true
}

// SetTranslations sets field value
func (o *FormatCreate) SetTranslations(v []FormatTranslation) {
	o.Translations = v
}

func (o FormatCreate) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.WorldId != nil {
		toSerialize["worldId"] = o.WorldId
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if true {
		toSerialize["translations"] = o.Translations
	}
	return json.Marshal(toSerialize)
}

type NullableFormatCreate struct {
	value *FormatCreate
	isSet bool
}

func (v NullableFormatCreate) Get() *FormatCreate {
	return v.value
}

func (v *NullableFormatCreate) Set(val *FormatCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableFormatCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableFormatCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFormatCreate(val *FormatCreate) *NullableFormatCreate {
	return &NullableFormatCreate{value: val, isSet: true}
}

func (v NullableFormatCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFormatCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


