/*
BMLT

BMLT Admin API Documentation

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bmlt

import (
	"encoding/json"
)

// MeetingCreate struct for MeetingCreate
type MeetingCreate struct {
	ServiceBodyId int32 `json:"serviceBodyId"`
	FormatIds []int32 `json:"formatIds"`
	VenueType int32 `json:"venueType"`
	TemporarilyVirtual *bool `json:"temporarilyVirtual,omitempty"`
	Day int32 `json:"day"`
	StartTime string `json:"startTime"`
	Duration string `json:"duration"`
	TimeZone *string `json:"timeZone,omitempty"`
	Latitude float32 `json:"latitude"`
	Longitude float32 `json:"longitude"`
	Published bool `json:"published"`
	Email *string `json:"email,omitempty"`
	WorldId *string `json:"worldId,omitempty"`
	Name string `json:"name"`
	LocationText *string `json:"location_text,omitempty"`
	LocationInfo *string `json:"location_info,omitempty"`
	LocationStreet *string `json:"location_street,omitempty"`
	LocationNeighborhood *string `json:"location_neighborhood,omitempty"`
	LocationCitySubsection *string `json:"location_city_subsection,omitempty"`
	LocationMunicipality *string `json:"location_municipality,omitempty"`
	LocationSubProvince *string `json:"location_sub_province,omitempty"`
	LocationProvince *string `json:"location_province,omitempty"`
	LocationPostalCode1 *string `json:"location_postal_code_1,omitempty"`
	LocationNation *string `json:"location_nation,omitempty"`
	PhoneMeetingNumber *string `json:"phone_meeting_number,omitempty"`
	VirtualMeetingLink *string `json:"virtual_meeting_link,omitempty"`
	VirtualMeetingAdditionalInfo *string `json:"virtual_meeting_additional_info,omitempty"`
	ContactName1 *string `json:"contact_name_1,omitempty"`
	ContactName2 *string `json:"contact_name_2,omitempty"`
	ContactPhone1 *string `json:"contact_phone_1,omitempty"`
	ContactPhone2 *string `json:"contact_phone_2,omitempty"`
	ContactEmail1 *string `json:"contact_email_1,omitempty"`
	ContactEmail2 *string `json:"contact_email_2,omitempty"`
	BusLines *string `json:"bus_lines,omitempty"`
	TrainLine *string `json:"train_line,omitempty"`
	Comments *string `json:"comments,omitempty"`
}

// NewMeetingCreate instantiates a new MeetingCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMeetingCreate(serviceBodyId int32, formatIds []int32, venueType int32, day int32, startTime string, duration string, latitude float32, longitude float32, published bool, name string) *MeetingCreate {
	this := MeetingCreate{}
	this.ServiceBodyId = serviceBodyId
	this.FormatIds = formatIds
	this.VenueType = venueType
	this.Day = day
	this.StartTime = startTime
	this.Duration = duration
	this.Latitude = latitude
	this.Longitude = longitude
	this.Published = published
	this.Name = name
	return &this
}

// NewMeetingCreateWithDefaults instantiates a new MeetingCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMeetingCreateWithDefaults() *MeetingCreate {
	this := MeetingCreate{}
	return &this
}

// GetServiceBodyId returns the ServiceBodyId field value
func (o *MeetingCreate) GetServiceBodyId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ServiceBodyId
}

// GetServiceBodyIdOk returns a tuple with the ServiceBodyId field value
// and a boolean to check if the value has been set.
func (o *MeetingCreate) GetServiceBodyIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServiceBodyId, true
}

// SetServiceBodyId sets field value
func (o *MeetingCreate) SetServiceBodyId(v int32) {
	o.ServiceBodyId = v
}

// GetFormatIds returns the FormatIds field value
func (o *MeetingCreate) GetFormatIds() []int32 {
	if o == nil {
		var ret []int32
		return ret
	}

	return o.FormatIds
}

// GetFormatIdsOk returns a tuple with the FormatIds field value
// and a boolean to check if the value has been set.
func (o *MeetingCreate) GetFormatIdsOk() ([]int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.FormatIds, true
}

// SetFormatIds sets field value
func (o *MeetingCreate) SetFormatIds(v []int32) {
	o.FormatIds = v
}

// GetVenueType returns the VenueType field value
func (o *MeetingCreate) GetVenueType() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.VenueType
}

// GetVenueTypeOk returns a tuple with the VenueType field value
// and a boolean to check if the value has been set.
func (o *MeetingCreate) GetVenueTypeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VenueType, true
}

// SetVenueType sets field value
func (o *MeetingCreate) SetVenueType(v int32) {
	o.VenueType = v
}

// GetTemporarilyVirtual returns the TemporarilyVirtual field value if set, zero value otherwise.
func (o *MeetingCreate) GetTemporarilyVirtual() bool {
	if o == nil || o.TemporarilyVirtual == nil {
		var ret bool
		return ret
	}
	return *o.TemporarilyVirtual
}

// GetTemporarilyVirtualOk returns a tuple with the TemporarilyVirtual field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MeetingCreate) GetTemporarilyVirtualOk() (*bool, bool) {
	if o == nil || o.TemporarilyVirtual == nil {
		return nil, false
	}
	return o.TemporarilyVirtual, true
}

// HasTemporarilyVirtual returns a boolean if a field has been set.
func (o *MeetingCreate) HasTemporarilyVirtual() bool {
	if o != nil && o.TemporarilyVirtual != nil {
		return true
	}

	return false
}

// SetTemporarilyVirtual gets a reference to the given bool and assigns it to the TemporarilyVirtual field.
func (o *MeetingCreate) SetTemporarilyVirtual(v bool) {
	o.TemporarilyVirtual = &v
}

// GetDay returns the Day field value
func (o *MeetingCreate) GetDay() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Day
}

// GetDayOk returns a tuple with the Day field value
// and a boolean to check if the value has been set.
func (o *MeetingCreate) GetDayOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Day, true
}

// SetDay sets field value
func (o *MeetingCreate) SetDay(v int32) {
	o.Day = v
}

// GetStartTime returns the StartTime field value
func (o *MeetingCreate) GetStartTime() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.StartTime
}

// GetStartTimeOk returns a tuple with the StartTime field value
// and a boolean to check if the value has been set.
func (o *MeetingCreate) GetStartTimeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartTime, true
}

// SetStartTime sets field value
func (o *MeetingCreate) SetStartTime(v string) {
	o.StartTime = v
}

// GetDuration returns the Duration field value
func (o *MeetingCreate) GetDuration() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Duration
}

// GetDurationOk returns a tuple with the Duration field value
// and a boolean to check if the value has been set.
func (o *MeetingCreate) GetDurationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Duration, true
}

// SetDuration sets field value
func (o *MeetingCreate) SetDuration(v string) {
	o.Duration = v
}

// GetTimeZone returns the TimeZone field value if set, zero value otherwise.
func (o *MeetingCreate) GetTimeZone() string {
	if o == nil || o.TimeZone == nil {
		var ret string
		return ret
	}
	return *o.TimeZone
}

// GetTimeZoneOk returns a tuple with the TimeZone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MeetingCreate) GetTimeZoneOk() (*string, bool) {
	if o == nil || o.TimeZone == nil {
		return nil, false
	}
	return o.TimeZone, true
}

// HasTimeZone returns a boolean if a field has been set.
func (o *MeetingCreate) HasTimeZone() bool {
	if o != nil && o.TimeZone != nil {
		return true
	}

	return false
}

// SetTimeZone gets a reference to the given string and assigns it to the TimeZone field.
func (o *MeetingCreate) SetTimeZone(v string) {
	o.TimeZone = &v
}

// GetLatitude returns the Latitude field value
func (o *MeetingCreate) GetLatitude() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Latitude
}

// GetLatitudeOk returns a tuple with the Latitude field value
// and a boolean to check if the value has been set.
func (o *MeetingCreate) GetLatitudeOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Latitude, true
}

// SetLatitude sets field value
func (o *MeetingCreate) SetLatitude(v float32) {
	o.Latitude = v
}

// GetLongitude returns the Longitude field value
func (o *MeetingCreate) GetLongitude() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Longitude
}

// GetLongitudeOk returns a tuple with the Longitude field value
// and a boolean to check if the value has been set.
func (o *MeetingCreate) GetLongitudeOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Longitude, true
}

// SetLongitude sets field value
func (o *MeetingCreate) SetLongitude(v float32) {
	o.Longitude = v
}

// GetPublished returns the Published field value
func (o *MeetingCreate) GetPublished() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Published
}

// GetPublishedOk returns a tuple with the Published field value
// and a boolean to check if the value has been set.
func (o *MeetingCreate) GetPublishedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Published, true
}

// SetPublished sets field value
func (o *MeetingCreate) SetPublished(v bool) {
	o.Published = v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *MeetingCreate) GetEmail() string {
	if o == nil || o.Email == nil {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MeetingCreate) GetEmailOk() (*string, bool) {
	if o == nil || o.Email == nil {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *MeetingCreate) HasEmail() bool {
	if o != nil && o.Email != nil {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *MeetingCreate) SetEmail(v string) {
	o.Email = &v
}

// GetWorldId returns the WorldId field value if set, zero value otherwise.
func (o *MeetingCreate) GetWorldId() string {
	if o == nil || o.WorldId == nil {
		var ret string
		return ret
	}
	return *o.WorldId
}

// GetWorldIdOk returns a tuple with the WorldId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MeetingCreate) GetWorldIdOk() (*string, bool) {
	if o == nil || o.WorldId == nil {
		return nil, false
	}
	return o.WorldId, true
}

// HasWorldId returns a boolean if a field has been set.
func (o *MeetingCreate) HasWorldId() bool {
	if o != nil && o.WorldId != nil {
		return true
	}

	return false
}

// SetWorldId gets a reference to the given string and assigns it to the WorldId field.
func (o *MeetingCreate) SetWorldId(v string) {
	o.WorldId = &v
}

// GetName returns the Name field value
func (o *MeetingCreate) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *MeetingCreate) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *MeetingCreate) SetName(v string) {
	o.Name = v
}

// GetLocationText returns the LocationText field value if set, zero value otherwise.
func (o *MeetingCreate) GetLocationText() string {
	if o == nil || o.LocationText == nil {
		var ret string
		return ret
	}
	return *o.LocationText
}

// GetLocationTextOk returns a tuple with the LocationText field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MeetingCreate) GetLocationTextOk() (*string, bool) {
	if o == nil || o.LocationText == nil {
		return nil, false
	}
	return o.LocationText, true
}

// HasLocationText returns a boolean if a field has been set.
func (o *MeetingCreate) HasLocationText() bool {
	if o != nil && o.LocationText != nil {
		return true
	}

	return false
}

// SetLocationText gets a reference to the given string and assigns it to the LocationText field.
func (o *MeetingCreate) SetLocationText(v string) {
	o.LocationText = &v
}

// GetLocationInfo returns the LocationInfo field value if set, zero value otherwise.
func (o *MeetingCreate) GetLocationInfo() string {
	if o == nil || o.LocationInfo == nil {
		var ret string
		return ret
	}
	return *o.LocationInfo
}

// GetLocationInfoOk returns a tuple with the LocationInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MeetingCreate) GetLocationInfoOk() (*string, bool) {
	if o == nil || o.LocationInfo == nil {
		return nil, false
	}
	return o.LocationInfo, true
}

// HasLocationInfo returns a boolean if a field has been set.
func (o *MeetingCreate) HasLocationInfo() bool {
	if o != nil && o.LocationInfo != nil {
		return true
	}

	return false
}

// SetLocationInfo gets a reference to the given string and assigns it to the LocationInfo field.
func (o *MeetingCreate) SetLocationInfo(v string) {
	o.LocationInfo = &v
}

// GetLocationStreet returns the LocationStreet field value if set, zero value otherwise.
func (o *MeetingCreate) GetLocationStreet() string {
	if o == nil || o.LocationStreet == nil {
		var ret string
		return ret
	}
	return *o.LocationStreet
}

// GetLocationStreetOk returns a tuple with the LocationStreet field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MeetingCreate) GetLocationStreetOk() (*string, bool) {
	if o == nil || o.LocationStreet == nil {
		return nil, false
	}
	return o.LocationStreet, true
}

// HasLocationStreet returns a boolean if a field has been set.
func (o *MeetingCreate) HasLocationStreet() bool {
	if o != nil && o.LocationStreet != nil {
		return true
	}

	return false
}

// SetLocationStreet gets a reference to the given string and assigns it to the LocationStreet field.
func (o *MeetingCreate) SetLocationStreet(v string) {
	o.LocationStreet = &v
}

// GetLocationNeighborhood returns the LocationNeighborhood field value if set, zero value otherwise.
func (o *MeetingCreate) GetLocationNeighborhood() string {
	if o == nil || o.LocationNeighborhood == nil {
		var ret string
		return ret
	}
	return *o.LocationNeighborhood
}

// GetLocationNeighborhoodOk returns a tuple with the LocationNeighborhood field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MeetingCreate) GetLocationNeighborhoodOk() (*string, bool) {
	if o == nil || o.LocationNeighborhood == nil {
		return nil, false
	}
	return o.LocationNeighborhood, true
}

// HasLocationNeighborhood returns a boolean if a field has been set.
func (o *MeetingCreate) HasLocationNeighborhood() bool {
	if o != nil && o.LocationNeighborhood != nil {
		return true
	}

	return false
}

// SetLocationNeighborhood gets a reference to the given string and assigns it to the LocationNeighborhood field.
func (o *MeetingCreate) SetLocationNeighborhood(v string) {
	o.LocationNeighborhood = &v
}

// GetLocationCitySubsection returns the LocationCitySubsection field value if set, zero value otherwise.
func (o *MeetingCreate) GetLocationCitySubsection() string {
	if o == nil || o.LocationCitySubsection == nil {
		var ret string
		return ret
	}
	return *o.LocationCitySubsection
}

// GetLocationCitySubsectionOk returns a tuple with the LocationCitySubsection field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MeetingCreate) GetLocationCitySubsectionOk() (*string, bool) {
	if o == nil || o.LocationCitySubsection == nil {
		return nil, false
	}
	return o.LocationCitySubsection, true
}

// HasLocationCitySubsection returns a boolean if a field has been set.
func (o *MeetingCreate) HasLocationCitySubsection() bool {
	if o != nil && o.LocationCitySubsection != nil {
		return true
	}

	return false
}

// SetLocationCitySubsection gets a reference to the given string and assigns it to the LocationCitySubsection field.
func (o *MeetingCreate) SetLocationCitySubsection(v string) {
	o.LocationCitySubsection = &v
}

// GetLocationMunicipality returns the LocationMunicipality field value if set, zero value otherwise.
func (o *MeetingCreate) GetLocationMunicipality() string {
	if o == nil || o.LocationMunicipality == nil {
		var ret string
		return ret
	}
	return *o.LocationMunicipality
}

// GetLocationMunicipalityOk returns a tuple with the LocationMunicipality field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MeetingCreate) GetLocationMunicipalityOk() (*string, bool) {
	if o == nil || o.LocationMunicipality == nil {
		return nil, false
	}
	return o.LocationMunicipality, true
}

// HasLocationMunicipality returns a boolean if a field has been set.
func (o *MeetingCreate) HasLocationMunicipality() bool {
	if o != nil && o.LocationMunicipality != nil {
		return true
	}

	return false
}

// SetLocationMunicipality gets a reference to the given string and assigns it to the LocationMunicipality field.
func (o *MeetingCreate) SetLocationMunicipality(v string) {
	o.LocationMunicipality = &v
}

// GetLocationSubProvince returns the LocationSubProvince field value if set, zero value otherwise.
func (o *MeetingCreate) GetLocationSubProvince() string {
	if o == nil || o.LocationSubProvince == nil {
		var ret string
		return ret
	}
	return *o.LocationSubProvince
}

// GetLocationSubProvinceOk returns a tuple with the LocationSubProvince field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MeetingCreate) GetLocationSubProvinceOk() (*string, bool) {
	if o == nil || o.LocationSubProvince == nil {
		return nil, false
	}
	return o.LocationSubProvince, true
}

// HasLocationSubProvince returns a boolean if a field has been set.
func (o *MeetingCreate) HasLocationSubProvince() bool {
	if o != nil && o.LocationSubProvince != nil {
		return true
	}

	return false
}

// SetLocationSubProvince gets a reference to the given string and assigns it to the LocationSubProvince field.
func (o *MeetingCreate) SetLocationSubProvince(v string) {
	o.LocationSubProvince = &v
}

// GetLocationProvince returns the LocationProvince field value if set, zero value otherwise.
func (o *MeetingCreate) GetLocationProvince() string {
	if o == nil || o.LocationProvince == nil {
		var ret string
		return ret
	}
	return *o.LocationProvince
}

// GetLocationProvinceOk returns a tuple with the LocationProvince field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MeetingCreate) GetLocationProvinceOk() (*string, bool) {
	if o == nil || o.LocationProvince == nil {
		return nil, false
	}
	return o.LocationProvince, true
}

// HasLocationProvince returns a boolean if a field has been set.
func (o *MeetingCreate) HasLocationProvince() bool {
	if o != nil && o.LocationProvince != nil {
		return true
	}

	return false
}

// SetLocationProvince gets a reference to the given string and assigns it to the LocationProvince field.
func (o *MeetingCreate) SetLocationProvince(v string) {
	o.LocationProvince = &v
}

// GetLocationPostalCode1 returns the LocationPostalCode1 field value if set, zero value otherwise.
func (o *MeetingCreate) GetLocationPostalCode1() string {
	if o == nil || o.LocationPostalCode1 == nil {
		var ret string
		return ret
	}
	return *o.LocationPostalCode1
}

// GetLocationPostalCode1Ok returns a tuple with the LocationPostalCode1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MeetingCreate) GetLocationPostalCode1Ok() (*string, bool) {
	if o == nil || o.LocationPostalCode1 == nil {
		return nil, false
	}
	return o.LocationPostalCode1, true
}

// HasLocationPostalCode1 returns a boolean if a field has been set.
func (o *MeetingCreate) HasLocationPostalCode1() bool {
	if o != nil && o.LocationPostalCode1 != nil {
		return true
	}

	return false
}

// SetLocationPostalCode1 gets a reference to the given string and assigns it to the LocationPostalCode1 field.
func (o *MeetingCreate) SetLocationPostalCode1(v string) {
	o.LocationPostalCode1 = &v
}

// GetLocationNation returns the LocationNation field value if set, zero value otherwise.
func (o *MeetingCreate) GetLocationNation() string {
	if o == nil || o.LocationNation == nil {
		var ret string
		return ret
	}
	return *o.LocationNation
}

// GetLocationNationOk returns a tuple with the LocationNation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MeetingCreate) GetLocationNationOk() (*string, bool) {
	if o == nil || o.LocationNation == nil {
		return nil, false
	}
	return o.LocationNation, true
}

// HasLocationNation returns a boolean if a field has been set.
func (o *MeetingCreate) HasLocationNation() bool {
	if o != nil && o.LocationNation != nil {
		return true
	}

	return false
}

// SetLocationNation gets a reference to the given string and assigns it to the LocationNation field.
func (o *MeetingCreate) SetLocationNation(v string) {
	o.LocationNation = &v
}

// GetPhoneMeetingNumber returns the PhoneMeetingNumber field value if set, zero value otherwise.
func (o *MeetingCreate) GetPhoneMeetingNumber() string {
	if o == nil || o.PhoneMeetingNumber == nil {
		var ret string
		return ret
	}
	return *o.PhoneMeetingNumber
}

// GetPhoneMeetingNumberOk returns a tuple with the PhoneMeetingNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MeetingCreate) GetPhoneMeetingNumberOk() (*string, bool) {
	if o == nil || o.PhoneMeetingNumber == nil {
		return nil, false
	}
	return o.PhoneMeetingNumber, true
}

// HasPhoneMeetingNumber returns a boolean if a field has been set.
func (o *MeetingCreate) HasPhoneMeetingNumber() bool {
	if o != nil && o.PhoneMeetingNumber != nil {
		return true
	}

	return false
}

// SetPhoneMeetingNumber gets a reference to the given string and assigns it to the PhoneMeetingNumber field.
func (o *MeetingCreate) SetPhoneMeetingNumber(v string) {
	o.PhoneMeetingNumber = &v
}

// GetVirtualMeetingLink returns the VirtualMeetingLink field value if set, zero value otherwise.
func (o *MeetingCreate) GetVirtualMeetingLink() string {
	if o == nil || o.VirtualMeetingLink == nil {
		var ret string
		return ret
	}
	return *o.VirtualMeetingLink
}

// GetVirtualMeetingLinkOk returns a tuple with the VirtualMeetingLink field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MeetingCreate) GetVirtualMeetingLinkOk() (*string, bool) {
	if o == nil || o.VirtualMeetingLink == nil {
		return nil, false
	}
	return o.VirtualMeetingLink, true
}

// HasVirtualMeetingLink returns a boolean if a field has been set.
func (o *MeetingCreate) HasVirtualMeetingLink() bool {
	if o != nil && o.VirtualMeetingLink != nil {
		return true
	}

	return false
}

// SetVirtualMeetingLink gets a reference to the given string and assigns it to the VirtualMeetingLink field.
func (o *MeetingCreate) SetVirtualMeetingLink(v string) {
	o.VirtualMeetingLink = &v
}

// GetVirtualMeetingAdditionalInfo returns the VirtualMeetingAdditionalInfo field value if set, zero value otherwise.
func (o *MeetingCreate) GetVirtualMeetingAdditionalInfo() string {
	if o == nil || o.VirtualMeetingAdditionalInfo == nil {
		var ret string
		return ret
	}
	return *o.VirtualMeetingAdditionalInfo
}

// GetVirtualMeetingAdditionalInfoOk returns a tuple with the VirtualMeetingAdditionalInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MeetingCreate) GetVirtualMeetingAdditionalInfoOk() (*string, bool) {
	if o == nil || o.VirtualMeetingAdditionalInfo == nil {
		return nil, false
	}
	return o.VirtualMeetingAdditionalInfo, true
}

// HasVirtualMeetingAdditionalInfo returns a boolean if a field has been set.
func (o *MeetingCreate) HasVirtualMeetingAdditionalInfo() bool {
	if o != nil && o.VirtualMeetingAdditionalInfo != nil {
		return true
	}

	return false
}

// SetVirtualMeetingAdditionalInfo gets a reference to the given string and assigns it to the VirtualMeetingAdditionalInfo field.
func (o *MeetingCreate) SetVirtualMeetingAdditionalInfo(v string) {
	o.VirtualMeetingAdditionalInfo = &v
}

// GetContactName1 returns the ContactName1 field value if set, zero value otherwise.
func (o *MeetingCreate) GetContactName1() string {
	if o == nil || o.ContactName1 == nil {
		var ret string
		return ret
	}
	return *o.ContactName1
}

// GetContactName1Ok returns a tuple with the ContactName1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MeetingCreate) GetContactName1Ok() (*string, bool) {
	if o == nil || o.ContactName1 == nil {
		return nil, false
	}
	return o.ContactName1, true
}

// HasContactName1 returns a boolean if a field has been set.
func (o *MeetingCreate) HasContactName1() bool {
	if o != nil && o.ContactName1 != nil {
		return true
	}

	return false
}

// SetContactName1 gets a reference to the given string and assigns it to the ContactName1 field.
func (o *MeetingCreate) SetContactName1(v string) {
	o.ContactName1 = &v
}

// GetContactName2 returns the ContactName2 field value if set, zero value otherwise.
func (o *MeetingCreate) GetContactName2() string {
	if o == nil || o.ContactName2 == nil {
		var ret string
		return ret
	}
	return *o.ContactName2
}

// GetContactName2Ok returns a tuple with the ContactName2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MeetingCreate) GetContactName2Ok() (*string, bool) {
	if o == nil || o.ContactName2 == nil {
		return nil, false
	}
	return o.ContactName2, true
}

// HasContactName2 returns a boolean if a field has been set.
func (o *MeetingCreate) HasContactName2() bool {
	if o != nil && o.ContactName2 != nil {
		return true
	}

	return false
}

// SetContactName2 gets a reference to the given string and assigns it to the ContactName2 field.
func (o *MeetingCreate) SetContactName2(v string) {
	o.ContactName2 = &v
}

// GetContactPhone1 returns the ContactPhone1 field value if set, zero value otherwise.
func (o *MeetingCreate) GetContactPhone1() string {
	if o == nil || o.ContactPhone1 == nil {
		var ret string
		return ret
	}
	return *o.ContactPhone1
}

// GetContactPhone1Ok returns a tuple with the ContactPhone1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MeetingCreate) GetContactPhone1Ok() (*string, bool) {
	if o == nil || o.ContactPhone1 == nil {
		return nil, false
	}
	return o.ContactPhone1, true
}

// HasContactPhone1 returns a boolean if a field has been set.
func (o *MeetingCreate) HasContactPhone1() bool {
	if o != nil && o.ContactPhone1 != nil {
		return true
	}

	return false
}

// SetContactPhone1 gets a reference to the given string and assigns it to the ContactPhone1 field.
func (o *MeetingCreate) SetContactPhone1(v string) {
	o.ContactPhone1 = &v
}

// GetContactPhone2 returns the ContactPhone2 field value if set, zero value otherwise.
func (o *MeetingCreate) GetContactPhone2() string {
	if o == nil || o.ContactPhone2 == nil {
		var ret string
		return ret
	}
	return *o.ContactPhone2
}

// GetContactPhone2Ok returns a tuple with the ContactPhone2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MeetingCreate) GetContactPhone2Ok() (*string, bool) {
	if o == nil || o.ContactPhone2 == nil {
		return nil, false
	}
	return o.ContactPhone2, true
}

// HasContactPhone2 returns a boolean if a field has been set.
func (o *MeetingCreate) HasContactPhone2() bool {
	if o != nil && o.ContactPhone2 != nil {
		return true
	}

	return false
}

// SetContactPhone2 gets a reference to the given string and assigns it to the ContactPhone2 field.
func (o *MeetingCreate) SetContactPhone2(v string) {
	o.ContactPhone2 = &v
}

// GetContactEmail1 returns the ContactEmail1 field value if set, zero value otherwise.
func (o *MeetingCreate) GetContactEmail1() string {
	if o == nil || o.ContactEmail1 == nil {
		var ret string
		return ret
	}
	return *o.ContactEmail1
}

// GetContactEmail1Ok returns a tuple with the ContactEmail1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MeetingCreate) GetContactEmail1Ok() (*string, bool) {
	if o == nil || o.ContactEmail1 == nil {
		return nil, false
	}
	return o.ContactEmail1, true
}

// HasContactEmail1 returns a boolean if a field has been set.
func (o *MeetingCreate) HasContactEmail1() bool {
	if o != nil && o.ContactEmail1 != nil {
		return true
	}

	return false
}

// SetContactEmail1 gets a reference to the given string and assigns it to the ContactEmail1 field.
func (o *MeetingCreate) SetContactEmail1(v string) {
	o.ContactEmail1 = &v
}

// GetContactEmail2 returns the ContactEmail2 field value if set, zero value otherwise.
func (o *MeetingCreate) GetContactEmail2() string {
	if o == nil || o.ContactEmail2 == nil {
		var ret string
		return ret
	}
	return *o.ContactEmail2
}

// GetContactEmail2Ok returns a tuple with the ContactEmail2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MeetingCreate) GetContactEmail2Ok() (*string, bool) {
	if o == nil || o.ContactEmail2 == nil {
		return nil, false
	}
	return o.ContactEmail2, true
}

// HasContactEmail2 returns a boolean if a field has been set.
func (o *MeetingCreate) HasContactEmail2() bool {
	if o != nil && o.ContactEmail2 != nil {
		return true
	}

	return false
}

// SetContactEmail2 gets a reference to the given string and assigns it to the ContactEmail2 field.
func (o *MeetingCreate) SetContactEmail2(v string) {
	o.ContactEmail2 = &v
}

// GetBusLines returns the BusLines field value if set, zero value otherwise.
func (o *MeetingCreate) GetBusLines() string {
	if o == nil || o.BusLines == nil {
		var ret string
		return ret
	}
	return *o.BusLines
}

// GetBusLinesOk returns a tuple with the BusLines field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MeetingCreate) GetBusLinesOk() (*string, bool) {
	if o == nil || o.BusLines == nil {
		return nil, false
	}
	return o.BusLines, true
}

// HasBusLines returns a boolean if a field has been set.
func (o *MeetingCreate) HasBusLines() bool {
	if o != nil && o.BusLines != nil {
		return true
	}

	return false
}

// SetBusLines gets a reference to the given string and assigns it to the BusLines field.
func (o *MeetingCreate) SetBusLines(v string) {
	o.BusLines = &v
}

// GetTrainLine returns the TrainLine field value if set, zero value otherwise.
func (o *MeetingCreate) GetTrainLine() string {
	if o == nil || o.TrainLine == nil {
		var ret string
		return ret
	}
	return *o.TrainLine
}

// GetTrainLineOk returns a tuple with the TrainLine field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MeetingCreate) GetTrainLineOk() (*string, bool) {
	if o == nil || o.TrainLine == nil {
		return nil, false
	}
	return o.TrainLine, true
}

// HasTrainLine returns a boolean if a field has been set.
func (o *MeetingCreate) HasTrainLine() bool {
	if o != nil && o.TrainLine != nil {
		return true
	}

	return false
}

// SetTrainLine gets a reference to the given string and assigns it to the TrainLine field.
func (o *MeetingCreate) SetTrainLine(v string) {
	o.TrainLine = &v
}

// GetComments returns the Comments field value if set, zero value otherwise.
func (o *MeetingCreate) GetComments() string {
	if o == nil || o.Comments == nil {
		var ret string
		return ret
	}
	return *o.Comments
}

// GetCommentsOk returns a tuple with the Comments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MeetingCreate) GetCommentsOk() (*string, bool) {
	if o == nil || o.Comments == nil {
		return nil, false
	}
	return o.Comments, true
}

// HasComments returns a boolean if a field has been set.
func (o *MeetingCreate) HasComments() bool {
	if o != nil && o.Comments != nil {
		return true
	}

	return false
}

// SetComments gets a reference to the given string and assigns it to the Comments field.
func (o *MeetingCreate) SetComments(v string) {
	o.Comments = &v
}

func (o MeetingCreate) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["serviceBodyId"] = o.ServiceBodyId
	}
	if true {
		toSerialize["formatIds"] = o.FormatIds
	}
	if true {
		toSerialize["venueType"] = o.VenueType
	}
	if o.TemporarilyVirtual != nil {
		toSerialize["temporarilyVirtual"] = o.TemporarilyVirtual
	}
	if true {
		toSerialize["day"] = o.Day
	}
	if true {
		toSerialize["startTime"] = o.StartTime
	}
	if true {
		toSerialize["duration"] = o.Duration
	}
	if o.TimeZone != nil {
		toSerialize["timeZone"] = o.TimeZone
	}
	if true {
		toSerialize["latitude"] = o.Latitude
	}
	if true {
		toSerialize["longitude"] = o.Longitude
	}
	if true {
		toSerialize["published"] = o.Published
	}
	if o.Email != nil {
		toSerialize["email"] = o.Email
	}
	if o.WorldId != nil {
		toSerialize["worldId"] = o.WorldId
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if o.LocationText != nil {
		toSerialize["location_text"] = o.LocationText
	}
	if o.LocationInfo != nil {
		toSerialize["location_info"] = o.LocationInfo
	}
	if o.LocationStreet != nil {
		toSerialize["location_street"] = o.LocationStreet
	}
	if o.LocationNeighborhood != nil {
		toSerialize["location_neighborhood"] = o.LocationNeighborhood
	}
	if o.LocationCitySubsection != nil {
		toSerialize["location_city_subsection"] = o.LocationCitySubsection
	}
	if o.LocationMunicipality != nil {
		toSerialize["location_municipality"] = o.LocationMunicipality
	}
	if o.LocationSubProvince != nil {
		toSerialize["location_sub_province"] = o.LocationSubProvince
	}
	if o.LocationProvince != nil {
		toSerialize["location_province"] = o.LocationProvince
	}
	if o.LocationPostalCode1 != nil {
		toSerialize["location_postal_code_1"] = o.LocationPostalCode1
	}
	if o.LocationNation != nil {
		toSerialize["location_nation"] = o.LocationNation
	}
	if o.PhoneMeetingNumber != nil {
		toSerialize["phone_meeting_number"] = o.PhoneMeetingNumber
	}
	if o.VirtualMeetingLink != nil {
		toSerialize["virtual_meeting_link"] = o.VirtualMeetingLink
	}
	if o.VirtualMeetingAdditionalInfo != nil {
		toSerialize["virtual_meeting_additional_info"] = o.VirtualMeetingAdditionalInfo
	}
	if o.ContactName1 != nil {
		toSerialize["contact_name_1"] = o.ContactName1
	}
	if o.ContactName2 != nil {
		toSerialize["contact_name_2"] = o.ContactName2
	}
	if o.ContactPhone1 != nil {
		toSerialize["contact_phone_1"] = o.ContactPhone1
	}
	if o.ContactPhone2 != nil {
		toSerialize["contact_phone_2"] = o.ContactPhone2
	}
	if o.ContactEmail1 != nil {
		toSerialize["contact_email_1"] = o.ContactEmail1
	}
	if o.ContactEmail2 != nil {
		toSerialize["contact_email_2"] = o.ContactEmail2
	}
	if o.BusLines != nil {
		toSerialize["bus_lines"] = o.BusLines
	}
	if o.TrainLine != nil {
		toSerialize["train_line"] = o.TrainLine
	}
	if o.Comments != nil {
		toSerialize["comments"] = o.Comments
	}
	return json.Marshal(toSerialize)
}

type NullableMeetingCreate struct {
	value *MeetingCreate
	isSet bool
}

func (v NullableMeetingCreate) Get() *MeetingCreate {
	return v.value
}

func (v *NullableMeetingCreate) Set(val *MeetingCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableMeetingCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableMeetingCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMeetingCreate(val *MeetingCreate) *NullableMeetingCreate {
	return &NullableMeetingCreate{value: val, isSet: true}
}

func (v NullableMeetingCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMeetingCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


