/*
BMLT

BMLT Admin API Documentation

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bmlt

import (
	"encoding/json"
)

// ServiceBodyPartialUpdate struct for ServiceBodyPartialUpdate
type ServiceBodyPartialUpdate struct {
	ParentId *int32 `json:"parentId,omitempty"`
	Name *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	Type *string `json:"type,omitempty"`
	AdminUserId *int32 `json:"adminUserId,omitempty"`
	AssignedUserIds []int32 `json:"assignedUserIds,omitempty"`
	Url *string `json:"url,omitempty"`
	Helpline *string `json:"helpline,omitempty"`
	Email *string `json:"email,omitempty"`
	WorldId *string `json:"worldId,omitempty"`
}

// NewServiceBodyPartialUpdate instantiates a new ServiceBodyPartialUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceBodyPartialUpdate() *ServiceBodyPartialUpdate {
	this := ServiceBodyPartialUpdate{}
	return &this
}

// NewServiceBodyPartialUpdateWithDefaults instantiates a new ServiceBodyPartialUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceBodyPartialUpdateWithDefaults() *ServiceBodyPartialUpdate {
	this := ServiceBodyPartialUpdate{}
	return &this
}

// GetParentId returns the ParentId field value if set, zero value otherwise.
func (o *ServiceBodyPartialUpdate) GetParentId() int32 {
	if o == nil || o.ParentId == nil {
		var ret int32
		return ret
	}
	return *o.ParentId
}

// GetParentIdOk returns a tuple with the ParentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceBodyPartialUpdate) GetParentIdOk() (*int32, bool) {
	if o == nil || o.ParentId == nil {
		return nil, false
	}
	return o.ParentId, true
}

// HasParentId returns a boolean if a field has been set.
func (o *ServiceBodyPartialUpdate) HasParentId() bool {
	if o != nil && o.ParentId != nil {
		return true
	}

	return false
}

// SetParentId gets a reference to the given int32 and assigns it to the ParentId field.
func (o *ServiceBodyPartialUpdate) SetParentId(v int32) {
	o.ParentId = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ServiceBodyPartialUpdate) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceBodyPartialUpdate) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ServiceBodyPartialUpdate) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ServiceBodyPartialUpdate) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ServiceBodyPartialUpdate) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceBodyPartialUpdate) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ServiceBodyPartialUpdate) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ServiceBodyPartialUpdate) SetDescription(v string) {
	o.Description = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ServiceBodyPartialUpdate) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceBodyPartialUpdate) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ServiceBodyPartialUpdate) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ServiceBodyPartialUpdate) SetType(v string) {
	o.Type = &v
}

// GetAdminUserId returns the AdminUserId field value if set, zero value otherwise.
func (o *ServiceBodyPartialUpdate) GetAdminUserId() int32 {
	if o == nil || o.AdminUserId == nil {
		var ret int32
		return ret
	}
	return *o.AdminUserId
}

// GetAdminUserIdOk returns a tuple with the AdminUserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceBodyPartialUpdate) GetAdminUserIdOk() (*int32, bool) {
	if o == nil || o.AdminUserId == nil {
		return nil, false
	}
	return o.AdminUserId, true
}

// HasAdminUserId returns a boolean if a field has been set.
func (o *ServiceBodyPartialUpdate) HasAdminUserId() bool {
	if o != nil && o.AdminUserId != nil {
		return true
	}

	return false
}

// SetAdminUserId gets a reference to the given int32 and assigns it to the AdminUserId field.
func (o *ServiceBodyPartialUpdate) SetAdminUserId(v int32) {
	o.AdminUserId = &v
}

// GetAssignedUserIds returns the AssignedUserIds field value if set, zero value otherwise.
func (o *ServiceBodyPartialUpdate) GetAssignedUserIds() []int32 {
	if o == nil || o.AssignedUserIds == nil {
		var ret []int32
		return ret
	}
	return o.AssignedUserIds
}

// GetAssignedUserIdsOk returns a tuple with the AssignedUserIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceBodyPartialUpdate) GetAssignedUserIdsOk() ([]int32, bool) {
	if o == nil || o.AssignedUserIds == nil {
		return nil, false
	}
	return o.AssignedUserIds, true
}

// HasAssignedUserIds returns a boolean if a field has been set.
func (o *ServiceBodyPartialUpdate) HasAssignedUserIds() bool {
	if o != nil && o.AssignedUserIds != nil {
		return true
	}

	return false
}

// SetAssignedUserIds gets a reference to the given []int32 and assigns it to the AssignedUserIds field.
func (o *ServiceBodyPartialUpdate) SetAssignedUserIds(v []int32) {
	o.AssignedUserIds = v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *ServiceBodyPartialUpdate) GetUrl() string {
	if o == nil || o.Url == nil {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceBodyPartialUpdate) GetUrlOk() (*string, bool) {
	if o == nil || o.Url == nil {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *ServiceBodyPartialUpdate) HasUrl() bool {
	if o != nil && o.Url != nil {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *ServiceBodyPartialUpdate) SetUrl(v string) {
	o.Url = &v
}

// GetHelpline returns the Helpline field value if set, zero value otherwise.
func (o *ServiceBodyPartialUpdate) GetHelpline() string {
	if o == nil || o.Helpline == nil {
		var ret string
		return ret
	}
	return *o.Helpline
}

// GetHelplineOk returns a tuple with the Helpline field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceBodyPartialUpdate) GetHelplineOk() (*string, bool) {
	if o == nil || o.Helpline == nil {
		return nil, false
	}
	return o.Helpline, true
}

// HasHelpline returns a boolean if a field has been set.
func (o *ServiceBodyPartialUpdate) HasHelpline() bool {
	if o != nil && o.Helpline != nil {
		return true
	}

	return false
}

// SetHelpline gets a reference to the given string and assigns it to the Helpline field.
func (o *ServiceBodyPartialUpdate) SetHelpline(v string) {
	o.Helpline = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *ServiceBodyPartialUpdate) GetEmail() string {
	if o == nil || o.Email == nil {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceBodyPartialUpdate) GetEmailOk() (*string, bool) {
	if o == nil || o.Email == nil {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *ServiceBodyPartialUpdate) HasEmail() bool {
	if o != nil && o.Email != nil {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *ServiceBodyPartialUpdate) SetEmail(v string) {
	o.Email = &v
}

// GetWorldId returns the WorldId field value if set, zero value otherwise.
func (o *ServiceBodyPartialUpdate) GetWorldId() string {
	if o == nil || o.WorldId == nil {
		var ret string
		return ret
	}
	return *o.WorldId
}

// GetWorldIdOk returns a tuple with the WorldId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceBodyPartialUpdate) GetWorldIdOk() (*string, bool) {
	if o == nil || o.WorldId == nil {
		return nil, false
	}
	return o.WorldId, true
}

// HasWorldId returns a boolean if a field has been set.
func (o *ServiceBodyPartialUpdate) HasWorldId() bool {
	if o != nil && o.WorldId != nil {
		return true
	}

	return false
}

// SetWorldId gets a reference to the given string and assigns it to the WorldId field.
func (o *ServiceBodyPartialUpdate) SetWorldId(v string) {
	o.WorldId = &v
}

func (o ServiceBodyPartialUpdate) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ParentId != nil {
		toSerialize["parentId"] = o.ParentId
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if o.AdminUserId != nil {
		toSerialize["adminUserId"] = o.AdminUserId
	}
	if o.AssignedUserIds != nil {
		toSerialize["assignedUserIds"] = o.AssignedUserIds
	}
	if o.Url != nil {
		toSerialize["url"] = o.Url
	}
	if o.Helpline != nil {
		toSerialize["helpline"] = o.Helpline
	}
	if o.Email != nil {
		toSerialize["email"] = o.Email
	}
	if o.WorldId != nil {
		toSerialize["worldId"] = o.WorldId
	}
	return json.Marshal(toSerialize)
}

type NullableServiceBodyPartialUpdate struct {
	value *ServiceBodyPartialUpdate
	isSet bool
}

func (v NullableServiceBodyPartialUpdate) Get() *ServiceBodyPartialUpdate {
	return v.value
}

func (v *NullableServiceBodyPartialUpdate) Set(val *ServiceBodyPartialUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceBodyPartialUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceBodyPartialUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceBodyPartialUpdate(val *ServiceBodyPartialUpdate) *NullableServiceBodyPartialUpdate {
	return &NullableServiceBodyPartialUpdate{value: val, isSet: true}
}

func (v NullableServiceBodyPartialUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceBodyPartialUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


